%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
# Camera calibration and distortion parameters (OpenCV) 
#+++++ Cam0 +++++
Camera.fx: 1068.4561767578125
Camera.fy: 1068.4561767578125
Camera.cx: 1103.111328125
Camera.cy: 632.1207275390625
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.000000
# Camera frames per second 
Camera.fps: 30.0
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0
#T_SC
Cam0.T00: 1.0
Cam0.T01: 0.0
Cam0.T02: 0.0
Cam0.T03: 0.0
Cam0.T10: 0.0
Cam0.T11: 1.0
Cam0.T12: 0.0
Cam0.T13: 0.0
Cam0.T20: 0.0
Cam0.T21: 0.0
Cam0.T22: 1.0
Cam0.T23: 0.0
Cam0.T30: 0.0
Cam0.T31: 0.0
Cam0.T32: 0.0
Cam0.T33: 1.0
